---
#- name: FreeIPA
 # hosts: domain
  #roles:

#- name: ForeMan
  #hosts: web
  #roles:


- name: monitoring
  hosts: zabbix
  tasks:
    - name: Установка docker
      block:
        - name: Добавляем universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Установка доппакетов
          apt:
            name:
              - apt-transport-https
              - ca-certificates 
              - curl 
              - gnupg 
              - lsb-release
            update-cache: true
            cache_valid_time: 86400

        - name: Добавление ключа докер
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg

        - name: Установка стабильного репозитория
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker

        - name: Установка Docker-ce
          apt:
            name: docker-ce
            update-cache: true

        - name: Проверка
          service:
            name: docker
            state: restarted
            enabled: true
      become: true

    - name: Установка docker-compose
      block:
        - name: Свежая версия
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
          
        - name: установка compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true

    - name: Завершение
      block: 
        - name: add user in group Docker
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

        - name: reboot
          reboot:
      become: true